export const CartActionTypes = {
	TOGGLE_SHOW_CART: "TOGGLE_SHOW_CART",
	ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
	REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
	CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART"
};
